#!/n/app/R/3.4.1/bin/Rscript

#  ****************************************************************************
#  activeClusterPairsRedux
#  Version 1.0
#  ****************************************************************************

#  Joseph Negri 
#  Original version 2019-01-04
#  Copyright is retained and must be preserved. 
#  The work is provided as is; no warranty is provided, and users accept all liability.

#  Script for determining which instances of sttc calculations between
#  spike cluster pairs have been successful completed, and generating an output
#  file containing those pairings still to be done.

#  this script accepts a two arugments:
#  * a 'activeClusterPairs.csv' generated by the activeClusterPairs.R
#  contains pairs spike clusters both active in a single well during
#  a MEA recording.
#  * a 'sttc.csv' generated by the sttc.R containing the
#  spike time tiling coefficients (STTC) calculated between two spike clusters
#  during a recording.

#  This script will return:
#  a .csv files 'activeClusterPairsRedux.csv' a subset of 
#  'activeClusterPairs.csv' limited to those pairs of clusters 
#  (rows) not represented in 'sttc.csv'

#  ########################################################

# write arguments to args vector
args <- commandArgs(trailingOnly = TRUE)

# load original activeClusterPairs to be processed
activeClusterPairs <-
  read.csv(
    args[1],
    header = FALSE
  )

# load sttc data completed thus far
sttcData <-
  read.csv(
    args[2],
    header = FALSE
  )

# clean up sttc data of bad rows
# typically the result of sloppy file concatenation
# with missing carriage return

# remove rows in which column 5 (sttc value) has a letter
sttcData <- 
  sttcData[which(grepl("[A-Z]",sttcData[,5])==FALSE),]

# remove rows in which column 5 (sttc value) lacks a number
sttcData <-
  sttcData[which(grepl("[0-9]",sttcData[,5])==TRUE),]

# generate vector of completed sttc calculations,
# designated by clusterA, clusterB, and rec
pairsToDo <- 
  paste(
    activeClusterPairs[,2],
    activeClusterPairs[,3],
    activeClusterPairs[,4],
    sep = "_"
    )

# generate vector of original sttc calculations to be done,
# designated by clusterA, clusterB, and rec
pairsDone <- 
  paste(
    sttcData[,2],
    sttcData[,3],
    sttcData[,4],
    sep = "_"
  )


activeClusterPairsRedux <-
  activeClusterPairs[which(c(pairsToDo %in% pairsDone)==FALSE),]

write.csv(
  activeClusterPairsRedux,
  paste0(Sys.Date(),"_activeClusterPairsRedux.csv")
)
