#!/n/app/R/3.4.1/bin/Rscript

#  ****************************************************************************
#  clusterFileRevision
#  Version 1.0
#  ****************************************************************************

#  Joseph Negri 
#  Original version 2018-12-18
#  Copyright is retained and must be preserved. 
#  The work is provided as is; no warranty is provided, and users accept all liability.

#  Script for revising clustered spike data, removing waveform voltages, leaving
#  timing and location data. Output used for calculating network activity where
#  voltage data is not required and small data file facilitates processing

#  this script accepts a one arugments:
#  * a .csv file e.g. 'wf.metrics.clustered.csv' generated by the
#  MEA_node-MS-cluster_v1.5.R script containing waveforms cluster by mean-shift
#  or similar technique. This clustering should have been done without
#  subsetting so all firing instances are present.

#  This script will return a .csv files 'wf.metrics.clustered.revised.csv'.

# libraries----
library("data.table", lib.loc="~/R-3.4.1/library")

# variables----

# write arguments to args vector
args <- commandArgs(trailingOnly = TRUE)

wfClustered <-
  fread(
    args[1]
  )

wfClustered[,`:=`(
  wellID=paste(plate.num,well_row,well_column,sep = "_"),
  nodeCluster=paste(node_ID,cluster,sep = "_"),
  node=node_ID
  ),
  .(node_ID)
  ]

wfClusteredRevised <-
  wfClustered[,.(
    plate.num,
    well_row,
    well_column,
    wellID,
    array_x,
    array_y,
    node,
    cluster,
    nodeCluster,
    rec,
    time
  )]

colnames(wfClusteredRevised) <- 
  c(
    "plateNum",
    "wellRow",
    "wellColumn",
    "wellID",
    "arrayX",
    "arrayY",
    "node",
    "cluster",
    "nodeCluster",
    "rec",
    "time"
  )

fwrite(
  wfClusteredRevised,
  paste0(Sys.Date(),"_wf.metrics.clustered.revised.csv")
  )
