#!/n/app/R/3.4.1/bin/Rscript

#  ****************************************************************************
#  MEA spk-cluster-metrics
#  Version 1.1
#  ****************************************************************************

#  Joseph Negri 
#  Original version 2018-03-22
#  Copyright is retained and must be preserved. 
#  The work is provided as is; no warranty is provided, and users accept all liability.

#  Script for compiling waveform cluster level metrics and voltage data from MEA
#  recording data following cluster analysis of waveforms by mean-shift,
#  k-means, or similar method

#  This script inputs two files. The first is a wf.metrics.clustered.csv file
#  generated by the spkClstrdAgg.sh script, which aggregates clustered waveform
#  data from individual electrodes into a single file. This
#  wf.metrics.clustered.csv file contains waveform level data consisting of
#  meta-data; including plate, well, node, recording, as well as the cluster to
#  which the spike as assigned, calculated waveform metrics; non-linear energy,
#  area-under-curve, amplitude, and interval, and finally the 38 momentary
#  voltage recordings constituting spike event. The second file is a
#  superactive_nodes.txt file, generated by the wf.cluster.number.triage.sh
#  script. This file contains a list of nodes (electrodes) which which had
#  record a large number of spike events (e.g. >10000) and thus a random sample
#  was used during the clustering analysis. Inclusion of this file is important
#  for back calculating the spike frequency of the clusters (i.e. individual
#  neurons) detected by this node.

#  This script should be executed from within the directory containing the
#  wf.metrics.clustered.csv and superactive_nodes.txt files. 

#  This script will return:
#   - clusterWfData.csv, a file of waveform-level data for only those spike
#   events within assigned clusters, containing associated meta-data, including
#   assigned cluster, and calculated waveform metrics and principle components,
#   but not momentary voltage recordings
#
#   - clusterWfVoltageLong.csv, a file of waveform-level data for only those
#   spike events within assigned clusters including voltage recordings in long
#   form, meaning a single voltage recording per line. This output is useful for
#   generating graphic depictions of waveforms
#
#   - clusterCentroids.csv, a file containing the coordinates of the calculated
#   center of each identified cluster as principle components (PC1, PC2)
#
#   - clusterData.csv, a file of waveform-level data for the spike determined to
#   be closest to the center of each cluster by euclidean distance containing
#   associated meta-data, including assigned cluster, and calculated waveform
#   metrics and principle components, but not momentary voltage recordings
#
#   - clusterVoltageLong.csv, a file of waveform-level data for the spike
#   determined to be closest to the center of each cluster by euclidean distance
#   containing voltage recordings in long form, meaning a single voltage
#   recording per line. This output is useful for generating graphic depictions
#   of waveforms

#  Update 2018-04-02 version 1.1

#  * eliminated clusterVolateLong.csv output. Output file is large (several GB)
#    and voltage data can be extracted from wf.clustered.csv if traces of individual
#    waveforms is required.

#  Update 2018-04-12 version 1.2

#  added recording duration as command line argument to faciliate analyzing 
#  recordings of different durations  

# load libraries----
library("data.table", lib.loc="~/R-3.4.1/library")
library(parallel)
# define variables----

# capture command line arguments
args <- commandArgs(trailingOnly = TRUE)

# recording duration in sec
durationSec <- as.integer(args[1])

# set threshold for num of spikes determining a superactive node
superactiveThres <- 10000

# set threshold for num of spikes determining a small cluster
smallClusterThres <- 10

# set the number of cores for parallel processing (unused)
# nCores <- as.integer(args[2])

# load waveform data with clustering annotation----
wfClusterDataDT <- fread(
  dir(pattern = "wf.metrics.clustered.csv"),
  stringsAsFactors = FALSE
)

wfClusterDataDT[well_row=="FALSE",well_row:="F"] # ensure row 'F' is not encoded as 'FALSE'
setnames(wfClusterDataDT,"node_ID","node") # rename node_ID for brevity
wfClusterDataDT[,`:=`(
  well=paste(well_row,well_column,sep = ""), #single identifier for well
  nodeCluster = paste(node,cluster,sep = "_"), #identifier for cluster on particular node
  nodeClusterRec = paste(node,cluster,rec,sep = "_") #identifier for cluster on particular node within recording
)]

# load superactive node data----
superactiveNodes <- data.table(
  read.delim(
    dir(pattern = "superactive_nodes.txt"),
    header = TRUE,
    sep = " ",
    stringsAsFactors = FALSE
  )
)

# identify cluster centers and determine spike frequency per cluster----

# calculate coefficient for each node
superactiveNodes[,spk_coeffiecient:=(line_count/superactiveThres),by="node"]

# determine to coordinates in PC space for the centroid of each cluster
clusterCentroidsQ <- wfClusterDataDT[,
                                     .(PC1=quantile(PC1,c(.5), na.rm = TRUE, TRUE, 3),
                                       PC2=quantile(PC2,c(.5), na.rm = TRUE, TRUE, 3)),
                                     by=.(nodeCluster)]

# calculate the number of spikes in each cluster
spikesPerClusterPerRecDT <- wfClusterDataDT[,.(spikesPerClusterRec=length(PC1)),by=.(nodeCluster,nodeClusterRec)]
spikesPerClusterDT <- wfClusterDataDT[,.(spikesPerCluster=length(PC1)),by=.(nodeCluster)]

# determine which clusters are 'small clusters'
smallClusters <- spikesPerClusterDT[spikesPerCluster<smallClusterThres,nodeCluster]

eachCluster <- unique(wfClusterDataDT[!nodeCluster %in% smallClusters,nodeCluster])

# exclude waveforms from small clusters
wfClusterDataDT <- wfClusterDataDT[!nodeCluster %in% smallClusters]

# add unique identifier for each spike
spkNum <- nrow(wfClusterDataDT)

wfClusterDataDT[,spikeID:=seq(1:spkNum)]

# exclude centroids of small clusters
clusterCentroidsQ <- clusterCentroidsQ[!nodeCluster %in% smallClusters]

# identify waveform within each cluster that is the closest euclidean distance to calculated center
clusterDataDT <- rbindlist(
  lapply(
    eachCluster,
    function(x){
      clusterCenter <-as.matrix(clusterCentroidsQ[nodeCluster==x][1,c(2,3)])
      clusterWfs <- as.matrix(wfClusterDataDT[nodeCluster==x,.(PC1,PC2)])
      clusterMatrix <- rbind(
        clusterCenter,
        clusterWfs
      )
      clusterEucDisMtrx <- as.matrix(stats::dist(clusterMatrix,method = "euclidean"))
      minEucDisIndex <- which.min(clusterEucDisMtrx[-1,1])[[1]]
      centerWF <- wfClusterDataDT[nodeCluster==x][minEucDisIndex]
      return(centerWF)
    }
  )
)

# remove columns which pertain to the 'center' waveform occurred but does not
# reflect the cluster as a whole
clusterDataDT[,c("SD","time","rec","nodeClusterRec","spikeID"):=NULL] 

clusterDataDT <- merge(clusterDataDT,spikesPerClusterPerRecDT,by="nodeCluster")

# determine spike frequency of each cluster per recording----

# for 'superactive' nodes, multiply the number of spikes by the corressponding coefficient for that node
sapply(clusterDataDT$node,
       function(x){
         if (x %in% superactiveNodes$node) {
           spk_coefficient = superactiveNodes[node==x,spk_coeffiecient]
           clusterDataDT[
             node==x,
             spikesAdjusted := as.integer(floor(spikesPerClusterRec*spk_coefficient))
             ]
         } else {
           clusterDataDT[
             node==x,
             spikesAdjusted := spikesPerClusterRec
             ]
         }
         return(NULL)
       }
)

clusterDataDT[,logHz:=log10(spikesAdjusted/durationSec)]

# reassign 'rec' to allow subsetting cluster metrics by recording
clusterDataDT[,rec:=strsplit(nodeClusterRec, split = "_")[[1]][5],by=.(nodeClusterRec)]

# remove spikesPerClusterRec, redundant after calculating spikesAdjusted
clusterDataDT[,spikesPerClusterRec:=NULL]

# reorder columns----
metadataCols <- c(
  "nodeCluster",
  "nodeClusterRec",
  "cluster",
  "plate.num",
  "well",
  "well_row",
  "well_column",
  "node",
  "array_x",
  "array_y",
  "rec"
)

dataCols <- c(
  "peak",
  "valley",
  "peak.valley",
  "pvi",
  "auc",
  "NLE.max",
  "PC1",
  "PC2",
  "PC3",
  "spikesAdjusted",
  "logHz"
)

voltCols <- paste0("V",c(1:38))

setcolorder(clusterDataDT,c(metadataCols,dataCols,voltCols))

# reformat tables: separate cluster voltages from cluster metrics----
wfDataCols <- dataCols[1:9]
wfMetadataCols <- c("spikeID",metadataCols)

wfData <- cbind(
  wfClusterDataDT[,..wfMetadataCols], #dt of metadata columns
  wfClusterDataDT[,..wfDataCols] #dt of wavform data columns
)

#wfVoltageWide <- cbind(
#  wfClusterDataDT[,..metadataCols], #dt of metadata columns
#  wfClusterDataDT[,..voltCols] #dt of voltage columns
#)

#wfVoltageLong <- melt.data.table(
#  wfVoltageWide,
#  measure.vars = voltCols,
#  variable.name = "Interval",
#  variable.factor = FALSE,
#  value.name = "uV")

# add time in milliseconds
#wfVoltageLong[,
#              timeInterval:=as.integer(
#                strsplit(Interval,split = "V")[[1]][2]
#              ),
#              by=.(Interval)]

#wfVoltageLong[,milliSec:=3*(timeInterval/max(timeInterval))]

clusterVoltageWide <- unique(clusterDataDT,by="nodeCluster")
clusterVoltageWide[,(dataCols):=NULL]
clusterVoltageWide[,c("nodeClusterRec","rec"):=NULL]

clusterVoltageLong <- melt.data.table(
  clusterVoltageWide,
  measure.vars = voltCols,
  variable.name = "Interval",
  variable.factor = FALSE,
  value.name = "uV")

# add time in milliseconds
clusterVoltageLong[,
                   timeInterval:=as.integer(
                     strsplit(Interval,split = "V")[[1]][2]
                   ),
                   by=.(Interval)]

clusterVoltageLong[,milliSec:=3*(timeInterval/max(timeInterval))]

# remove voltages from cluster
clusterDataDT[,(voltCols):=NULL]

# write outputs----
experiment <- strsplit(basename(getwd()),split = "_")[[1]][-1]
experiment <- paste(experiment, collapse = "_")

# clustered waveforms metrics
fwrite(
  wfData,
  file = paste(
    Sys.Date(),
    experiment,
    "clusterWfData.csv",
    sep="_"
  ),
  row.names = FALSE
)

# clustered waveforms voltages
#fwrite(
#  wfVoltageLong,
#  file = paste(
#    Sys.Date(),
#    experiment,
#    "clusterWfVoltageLong.csv",
#    sep="_"
#  ),
#  row.names = FALSE
#)

# cluster centroids
fwrite(
  clusterCentroidsQ,
  file = paste(
    Sys.Date(),
    experiment,
    "clusterCentroids.csv",
    sep="_"
  ),
  row.names = FALSE
)

# cluster voltages
fwrite(
  clusterVoltageLong,
  file = paste(
    Sys.Date(),
    experiment,
    "clusterVoltageLong.csv",
    sep="_"
  ),
  row.names = FALSE
)

# cluster data
fwrite(
  clusterDataDT,
  file = paste(
    Sys.Date(),
    experiment,
    "clusterData.csv",
    sep="_"
  ),
  row.names = FALSE
)
